name: Build mod jar

on:
  [workflow_dispatch, push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Set up JDK new
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'temurin'
    - uses: gradle/actions/setup-gradle@v6
      with:
        gradle-version: 9.6.1
      name: Set up Gradle
    - name: Add permission
      run: chmod +x ./gradlew
    - name: Setup
      run: ./gradlew setupDecompWorkspace
    - name: Execute Gradle build
      run: ./gradlew build
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7
      with:
        path: build/libs
